# argocd-application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  # This name will appear in the Argo CD UI
  name: my-test-app
  namespace: argocd
spec:
  project: default
  source:
    # IMPORTANT: Change this to your repository's URL
    repoURL: "https://github.com/vijai-veerapandian/argocd-with-kind-deployments.git"

    # This points to the folder with your deployment.yaml
    path: test-app

    targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc" # Deploys to the same cluster

    # Your deployment will be created in the 'default' namespace
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
