# argocd-basic-app.yaml

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: basic-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/vijai-veerapandian/argocd-with-kind-deployments.git'
    path: basic-app
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
