# kind-config.yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30007 # The NodePort we will configure for Argo CD
        hostPort: 30007 # The port on your localhost
        protocol: TCP
