# basic-app/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-basic-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-basic-app
  template:
    metadata:
      labels:
        app: my-basic-app
    spec:
      containers:
      - name: basic-app
        image: nginxdemos/hello:plain-text
