# test-app/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-test-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-test-app
  template:
    metadata:
      labels:
        app: my-test-app
    spec:
      containers:
        - name: test-app
          image: kennethreitz/httpbin # A simple HTTP testing service
